### ISSUE TITLE
File pointer qmeasfile is closed without being initialized.

### ISSUE THREAD

**Issue by fmuzf** [regine/meltmodel#43]
On Fedora 20, [closeall.c:383](https://github.com/regine/meltmodel/blob/c3cb365844ff6c5fdb45b81fa7c5c45f02fb04d6/src/closeall.c#L383) seg-faults.

After a little searching around, I can see that the pointed is defined in the variab.h and variabex.h, but can't find any place where the file is opened or the pointer initialized. My quick look around suggests to me that the data formerly in this file has since been moved into the climate-data file. Is this correct, and if so, can we remove all traces of the file from the code?

**Comment by regine** [comment]
Yes, that is correct. I moved the measured discharge (qmeas) information to the climate data file. So, this can be removed.
/Regine


On Jan 21, 2015, at 9:57, Lyman Gillispie <notifications@github.com> wrote:

> On Fedora 20, closeall.c:383 seg-faults.
> 
> After a little searching around, I can see that the pointed is defined in the variab.h and variabex.h, but can't find any place where the file is opened or the pointer initialized. My quick look around suggests to me that the data formerly in this file has since been moved into the climate-data file. Is this correct, and if so, can we remove all traces of the file from the code?
> 
> —
> Reply to this email directly or view it on GitHub.
> 



------------------------------------------
Regine Hock
Geophysical Institute
University of Alaska
903 Koyukuk Dr.
Fairbanks, Alaska 99775-7320
ph: 907 - 474 7691
fax: 907 - 474 5882
regine@gi.alaska.edu
------------------------------------------

**Comment by fmuzf** [comment]
Closed by 1565c2af709c5b122c8c44373d9d0b1d7c183c69
