### ISSUE TITLE
Type mismatch on call to statist in writeout.c

### ISSUE THREAD

**Issue by fmuzf** [regine/meltmodel#45]
In writeout.c there's [a call](https://github.com/regine/meltmodel/blob/1565c2af709c5b122c8c44373d9d0b1d7c183c69/src/writeout.c#L969) to ```statist``` which passes the ```**double``` ```watercontent```, but ```statist``` has signature 
```void statist(float **matrix,float *x)```.

Is there an equivalent to ```statist``` that manipulates double arrays? If so this should be fixed.

**Comment by regine** [comment]
On Jan 21, 2015, at 11:40, Lyman Gillispie <notifications@github.com> wrote:

> In writeout.c there's a call to statist which passes the **double watercontent, but statist has signature 
> void statist(float **matrix,float *x).
> 
> Is there an equivalent to statist that manipulates double arrays? If so this should be fixed.

good point. I guess that is an easy one to fix:
copying the function, calling itstatist double and adding the header to function h.

You wanna do that?

/Regine


------------------------------------------
Regine Hock
Geophysical Institute
University of Alaska
903 Koyukuk Dr.
Fairbanks, Alaska 99775-7320
ph: 907 - 474 7691
fax: 907 - 474 5882
regine@gi.alaska.edu
------------------------------------------

**Comment by fmuzf** [comment]
I looked around, and there's an identical-up-to-signature method called ```statistdouble``` located in ```snowmodel.c``` [here](https://github.com/regine/meltmodel/blob/1565c2af709c5b122c8c44373d9d0b1d7c183c69/src/snowmodel.c#L52-L81).

For organization's sake, if these do identical work for different types, it would make sense to put them in the same source file so that down the road it's easy to see that they both exist. I'm not totally sure where they would most belong: both in ```writeout.c``` or both in some third "statist" (or whatever) file.
