### ISSUE TITLE
Certain compiler-flag/OS combinations cause models to crash

### ISSUE THREAD

**Issue by fmuzf** [regine/meltmodel#46]
We've had issues compiling on OS X
* OS X 10.6 compiled without -m32
* OS X 10.8 compiled with -m32 
* Ubuntu linux 12.4  compiled with -m32

In the past, OS X 10.6 would segfault unless -m32 was specified, this appears to no longer be the problem, at least in OS 10.8, and linux in general.

**Comment by fmuzf** [comment]
This should be fixed in v2.1.2, closing.

**Comment by regine** [comment]
how do I upload a new README-web.html?
the instruction dont work?


On Jan 29, 2015, at 14:26, Lyman Gillispie <notifications@github.com> wrote:

> This should be fixed in v2.1.2, closing.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



------------------------------------------
Regine Hock
Geophysical Institute
University of Alaska
903 Koyukuk Dr.
Fairbanks, Alaska 99775-7320
ph: 907 - 474 7691
fax: 907 - 474 5882
regine@gi.alaska.edu
------------------------------------------
